# Generated by Django 4.2.6 on 2023-12-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_gallery_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="year",
            name="year_id",
            field=models.IntegerField(default=0),
        ),
    ]
