# Generated by Django 4.2.6 on 2023-12-23 15:59

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_year_year_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("slug", models.SlugField(default="", max_length=1000)),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                ("video_url", models.URLField(max_length=2000)),
                (
                    "year",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.year",
                    ),
                ),
            ],
        ),
    ]
