apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: galerie
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
  selector:
    matchLabels:
      storage-type: db-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
  namespace: galerie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            valueFrom: 
              configMapKeyRef:
                name: env-configmap
                key: db-name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: db-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: db-password
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-service
  namespace: galerie
spec:
  selector:
      app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
