name: CI-dev
on:
  push:
    branches:
      - dev
jobs:
  lint-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install linter
        run: pip install black flake8 isort
      - name: Lint
        run: black . --check && isort . --profile black && flake8 . --config .github/linters/.flake8